[Draft] Feat: adminjs 추가, Category, User 시범 적용
42-world/42world-Backend pull request #140
Opened 2022-03-15 15:34 UTC by rockpell

## 바뀐점
- adminjs를 추가

## 바꾼이유
- 편하게 admin을 사용하기 위해 적용

## 설명
- adminjs에서 crud가 되려면 base entity를 상속받은 entity가 필요하다
- base entity를 상속받아도 문제가 적었던 category, user entity만 우선적으로 적용
- 다른 entity는 여러 코드에서 에러가 나서 dto 적용 후 전환 예정

2022-03-15 23:31 UTC, Skyrich2000 commented
헉 벌써하셨군요 빠르십니다

2022-03-16 06:02 UTC, Skyrich2000 reviewed
<img width="1199" alt="image" src="https://user-images.githubusercontent.com/46391729/158526537-33fc9f18-eb85-4587-bccb-0d0a32cb403c.png">
실행해보면 이런 에러가..? 뭔가 잘못 설치된걸까요...

2022-03-16 12:03 UTC, rockpell commented on .adminjs/.entry.js
> +AdminJS.UserComponents = {}
이거는 adminjs 추가하면 자동으로 생기던데 저도 뭔지 아직 모르겠네요
커스텀해서 쓸때 필요한거 같긴한데

2022-03-16 12:12 UTC, rockpell commented on src/user/user.service.ts
>      };
바로 반영했습니다!

2022-04-18 06:49 UTC, Yaminyam commented
변경된 구조에 맞게 import 수정하였습니다
unused variable 제거했습니다
혹시 아직 완성되지 않은 코드인데 지운걸까요??

2022-04-18 17:12 UTC, blingblin-g commented on apps/admin/src/adminJs/admin-js.module.ts
> +          },
계정은 따로 설정하는 게 좋을 것 같아요. 예를 들면 env 파일 같은 걸로?

2022-04-18 17:13 UTC, blingblin-g commented on apps/admin/src/main.ts
> +  await app.listen(3000);
몇가지 궁금한 점이 있습니다~
1. 포트 번호는 이렇게 명시해도 상관 없나요?
2. 포트 번호는 다른 앱과 겹쳐도 상관 없나요?

2022-04-18 17:18 UTC, blingblin-g commented on apps/admin/src/adminJs/admin-js.module.ts
> +            rootPath: '/admin',
url을 찾지 못하게 숨기고 특정하기 어려운 단어로 바꾸면 보안 상 더 좋을 것 같아요.

2022-04-18 17:20 UTC, blingblin-g requested changes
soft delete를 했을 경우에는 보이고, hard delete를 했을 경우에만 영원히 사라지게 하면 좋을 것 같아요. 뭔가 방법이 있을까요?

2022-04-19 17:08 UTC, rockpell commented on apps/admin/src/adminJs/admin-js.module.ts
> +            rootPath: '/admin',
적용하였습니다!

2022-04-19 17:22 UTC, rockpell commented on apps/admin/src/main.ts
> +  await app.listen(3000);
env로 받도록 수정했습니다
포트 번호는 안겹치게 하는게 좋을거 같아요

2022-04-20 14:10 UTC, rockpell commented
> soft delete를 했을 경우에는 보이고, hard delete를 했을 경우에만 영원히 사라지게 하면 좋을 것 같아요. 뭔가 방법이 있을까요?

찾아봤는데 방법을 못찾겠네요
나중에 어드민 직접 제작할때까지는 그냥 써야할거 같아요

2022-04-20 14:11 UTC, rockpell commented
> 변경된 구조에 맞게 import 수정하였습니다 unused variable 제거했습니다 혹시 아직 완성되지 않은 코드인데 지운걸까요??

그렇긴한데 큰문제 없습니다!

2022-04-24 14:25 UTC, mimseong approved these changes

2022-04-24 14:25 UTC, blingblin-g approved these changes
soft delete 핸들링이 안되는 점은 아쉽네요. 고생하셨습니다~

2022-04-24 14:25 UTC, rockpell commented on .adminjs/.entry.js
> +AdminJS.UserComponents = {}
알아보니 리액트 컴포넌트를 추가할수 있는 파일입니다

2022-04-24 14:28 UTC, Skyrich2000 approved these changes
soft delete가 아쉽지만 하나있는거 좋네요

2022-04-24 14:28 UTC, Skyrich2000 commented on apps/admin/src/adminJs/admin-js.module.ts
> +            rootPath: configService.get('ADMIN_URL'),
env를 다 configService 로 바꿨군요 좋은거같아요

2022-04-24 14:29 UTC, raejun92 approved these changes
멋저요

2022-04-24 14:30 UTC, merged