Feature: 응답 httpcode를 201에서 200으로 나오게 변경
42-world/42world-Backend pull request #166
Opened 2022-04-06 09:06 UTC by Skyrich2000

## 바뀐점
intra-auth
image
reation
에 대해서 POST 요청의 http응답코드가 201이였던걸 200으로 변경하였습니다.

## 바꾼이유
POST이지만, 의미상 유의미한 리소스가 생성되는 api요청은 아니기때문에 200으로 하였습니다.

## 설명
근데 조금 애매하긴하네요.. 그냥 201로 둬도 될거같기도하고... 
특히 reation은 버튼을 누를때마다 리액션이 생성되기도 하고 없어지기도 해서 그냥 PUT으로 바꾸는게 좀더 맞는거같다는 생각이 드네요

2022-04-07 01:16 UTC, Yaminyam commented
애매하긴 하지만 그래두 확실히 post보다는 put이 더 가깝다고 생각이되네요

2022-04-07 01:20 UTC, Yaminyam reviewed
200, 201과 같이 응답코드가 들어가는 부분을 HttpStatus.OK와 HttpStatus.Created로 명시적으로 표기하면 좋을것 같습니다.

2022-04-07 02:13 UTC, mimseong commented
깃 노티 테스트

2022-04-07 02:27 UTC, mimseong commented
깃 노티 테스트

2022-04-07 06:46 UTC, Skyrich2000 commented
> 200, 201과 같이 응답코드가 들어가는 부분을 HttpStatus.OK와 HttpStatus.Created로 명시적으로 표기하면 좋을것 같습니다.

이거는 #167 이랑 머지할때 변경하도록 할게요

2022-04-07 16:10 UTC, rockpell commented
이미지 업로드 url 생성은 db에 값을 생성하는 행동은 아니지만 일정 기간동안 접근 가능한 url을 생성하는거라서 201로 봐도 되지 않을까요?

2022-04-07 16:19 UTC, Skyrich2000 commented
> 이미지 업로드 url 생성은 db에 값을 생성하는 행동은 아니지만 일정 기간동안 접근 가능한 url을 생성하는거라서 201로 봐도 되지 않을까요?

실제로 이미지를 업로드는건 아니라서 200이라고 생각했는데, url을 생성하긴했으니 201이라고 봐도 될거같기도 하네요...

2022-04-08 13:44 UTC, blingblin-g requested changes
200말고 `httpStatus.OK`로 바꾸면 좋을 것 같아요.

2022-04-08 13:56 UTC, blingblin-g approved these changes
제가 바꿨습니다~

2022-04-08 13:57 UTC, raejun92 approved these changes

2022-04-08 13:57 UTC, rockpell approved these changes

2022-04-08 13:57 UTC, merged