Chore: Windows end of line lint
42-world/42world-Backend pull request #227
Opened 2022-05-07 14:47 UTC by Yaminyam

## 바뀐점
eslint prettier의 endofline 설정 auto로 변경

## 바꾼이유
Windows 에서는 줄바꿈으로 CRLF를 사용하여 오류가 발생해 Windows 개발환경에서도 개발 할 수 있도록 수정

## 설명

2022-05-07 15:00 UTC, Skyrich2000 requested changes

2022-05-07 15:00 UTC, Skyrich2000 commented on .eslintrc.js
> +	'prettier/prettier': ["error", { "endOfLine": "auto" }],
탭이 안맞아서 조금 킹받네요 ㅎㅎ..
스페이스 4개가 맞는거같습니다

2022-05-07 15:01 UTC, Yaminyam commented on .eslintrc.js
> +	'prettier/prettier': ["error", { "endOfLine": "auto" }],
으악 그러네요 수정하겠습니다

2022-05-07 15:02 UTC, Yaminyam commented on .eslintrc.js
> +	'prettier/prettier': ["error", { "endOfLine": "auto" }],
Vscode에서는 똑같이 보이는데 github오면 바로 티나더라구요

2022-05-08 14:24 UTC, Skyrich2000 approved these changes
수정된거 좋습니당

2022-05-08 14:24 UTC, raejun92 approved these changes
렛츠고 윈도우

2022-05-08 14:25 UTC, merged