센트리인터셉터 이동 및 batch에 센트리 적용
42-world/42world-Backend pull request #236
Opened 2022-05-15 04:43 UTC by raejun92

- apps/api 에서 libs/common/src/interceptor 로 이동
- batch에 센트리인터셉터 적용(테스트x)

2022-06-22 13:53 UTC, Skyrich2000 approved these changes
config service 도 추가해서 env를 적용해야할거같네요

2022-06-22 13:55 UTC, rockpell requested changes
Sentry.init 랑
env 가져오는 기능도 추가해야할거 같네요

2022-06-26 18:12 UTC, Skyrich2000 approved these changes
sentry init 추가되었네요 좋습니다!

2022-06-29 13:36 UTC, Skyrich2000 commented on apps/batch/src/main.ts
> +  const configService = app.get(ConfigService);
지금 보니까 여기서 ConfigService를 가져오려면 batch.module.ts 에서 ConfigServie를 import 해서 써야할것같습니다.

2022-07-03 15:12 UTC, Yaminyam commented
왜 테스트가 무한으로 돌고있죠...ㄷ

2022-07-03 15:13 UTC, Yaminyam approved these changes

2022-07-04 14:48 UTC, Skyrich2000 commented on apps/batch/src/batch.module.ts
> +      load: [ormconfig, configEmail],
batch 에서는 typeorm 과 email 서비스를 사용하지 않기 때문에 load 에서 가져오지 않아도 될것같습니다.

2022-07-09 07:51 UTC, raejun92 commented on apps/batch/src/batch.module.ts
> +      load: [ormconfig, configEmail],
그렇군요 감사합니다 : )

2022-07-16 14:37 UTC, rockpell approved these changes

2022-07-16 14:37 UTC, blingblin-g approved these changes
LGTM 👍

2022-07-16 14:37 UTC, merged